name: Terraform platform deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment you want to deploy to from the dropdown list
        options:
          - tf-backend
          - platform
permissions:
  id-token: write
  contents: write
jobs:
  terraform-deployment:
    uses: nationalarchives/tre-github-actions/.github/workflows/tf-plan-approve-apply.yml@0.0.5
    with:
      environment: ${{ inputs.environment }}
      environment-for-approval: apply-tf-plan-${{ inputs.environment }}
      tf_dir: ${{ inputs.environment }}
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
