name: Terraform platform plan
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment you want to generate a terraform plan for from the dropdown list
        options:
          - tf-backend
          - platform
      github_action_ref:
        description: tre-github-action repo ref
        type: string
        required: false
        default: main
permissions:
  id-token: write
  contents: write
jobs:
  terraform-deployment:
    uses: nationalarchives/da-tre-github-actions/.github/workflows/tf-plan.yml@DTE-913-platform-plan-action
    with:
      github_environment: ${{ inputs.environment }}-plan
      tre_environment: ${{ inputs.environment }}
      tf_dir: ${{ inputs.environment }}
      github_action_ref: ${{ inputs.github_action_ref }}
    secrets:
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_PARAM_STORE_TF_BACKEND_KEY: ${{ secrets.AWS_PARAM_STORE_TF_BACKEND_KEY }}
